### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by luxorko** [shaxxx/epg#1]
please see log from enigma:
`18:49:04.4927 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:04+0100 [-] [Screen] Showing screen 'SetupSummary'.
18:49:04.4951 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:04+0100 [-] [Screen] Showing screen 'EPGImportConfig'.
18:49:04.5004 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:04+0100 [-] [EPGImport] nextImport, source= ExYu Channels By Nuno
18:49:04.5012 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:04+0100 [-] [EPGImport] Downloading: https://raw.githubusercontent.com/shaxxx/epg/raw/main/output/nuno.xml.gz to local path: /tmp/epgimport.gz
18:49:06.0494 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [EPGImport] No IPv6, using IPv4 directly: https://raw.githubusercontent.com/shaxxx/epg/raw/main/output/nuno.xml.gz
18:49:06.0524 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] Starting factory <HTTPDownloader: https://raw.githubusercontent.com/shaxxx/epg/raw/main/output/nuno.xml.gz>
18:49:06.0544 driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
18:49:06.0614 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] KEY: 352 1 KEY_OK OK
18:49:06.4464 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [EPGImport] download failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.web.error.Error'>: 404 Not Found
18:49:06.4469 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] ]
18:49:06.4475 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [EPGImport] imported 0 events
18:49:06.4514 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [XMLTVImport] Save last import date and count event
18:49:06.4520 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [XMLTVImport] Run check deep standby after import
18:49:06.4526 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] [EPGImport] #### Finished ####
18:49:06.4537 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-07-25 18:49:06+0100 [-] Stopping factory <HTTPDownloader: https://raw.githubusercontent.com/shaxxx/epg/raw/main/output/nuno.xml.gz>
`
`

**Comment by shaxxx** [comment]
Your URL is invalid? How did you come up with this url?
Use krkadoni.sources.xml file from this repository.
https://github.com/shaxxx/epg/raw/main/output/nuno.xml.gz works as expected.
